name: CI Backend Karsajobs

on:
  push:
    branches: [ "karsajobs" ]

env:
  # Mengatasi peringatan deprecation Node.js 20 di tahun 2026
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/karsajobs

jobs:
  pipeline:
    runs-on: ubuntu-latest
    # Menambahkan izin eksplisit untuk membaca konten dan menulis paket
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Lint Dockerfile menggunakan Hadolint
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      # Unit Testing untuk Backend Go
      - name: Run Backend Tests
        run: go test -v -short --count=1 $(go list ./...)

      # Login ke GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build dan Push Image ke GHCR
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest