name: CI Frontend Karsa Jobs UI

on:
  push:
    branches: [ "karsajobs-ui" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 

      # Kriteria Saran: Lint Dockerfile
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      # Kriteria Saran: Unit Test Backend
      - name: Run Backend Tests
        run: go test -v -short --count=1 $(go list ./...)

      # Login ke GitHub Packages (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5 
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/karsajobs-ui:latest